<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>WelcomeBot</AssemblyName>
    <RootNamespace>WelcomeBot</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>

    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>

    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <EventSourceSupport>false</EventSourceSupport>
    <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
    <MetadataUpdaterSupport>false</MetadataUpdaterSupport>

    <InvariantGlobalization>true</InvariantGlobalization>
    <UseSystemResourceKeys>true</UseSystemResourceKeys>

    <DebuggerSupport>false</DebuggerSupport>
    <StackTraceSupport>true</StackTraceSupport>

    <TieredPGO>false</TieredPGO>
    <TieredCompilation>true</TieredCompilation>
    <TieredCompilationQuickJit>true</TieredCompilationQuickJit>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Discord.Net.WebSocket" Version="3.19.1" />
    <PackageReference Include="Discord.Net.Rest" Version="3.19.1" />
    <PackageReference Include="DotNetEnv" Version="3.2.0" />
    <PackageReference Include="PuppeteerSharp" Version="25.3.3" />
  </ItemGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="Discord.Net.WebSocket" />
    <TrimmerRootAssembly Include="Discord.Net.Rest" />
    <TrimmerRootAssembly Include="Discord.Net.Core" />
    <TrimmerRootAssembly Include="PuppeteerSharp" />
  </ItemGroup>
</Project>
